version: '3'

#name: deyapps-environment
services:
  sonarqube:
    container_name: sonarqube
    image: sonarqube:25.3.0.104237-community
    command: "-Dsonar.search.javaAdditionalOpts=-Dnode.store.allow_mmap=false"
    depends_on:
      - db
    environment: #admin/Admin123????
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
    volumes:
      - sonarqube-conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube-bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    ports:
      - "9001:9000"
    networks:
      - network_ci

  db:
    container_name: sonarqube_db
    image: postgres:17
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql17:/var/lib/postgresql
      - postgresql17_data:/var/lib/postgresql/data
    networks:
      - network_ci
  jenkins-docker:
    container_name: jenkins-docker
    build: 
      context: ./docker-files/
      dockerfile: Dockerfile-jenkins
    ports:
      - "9002:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - network_ci
  nginx-ssh:
    container_name: nginx-ssh
    build: 
      context: ./docker-files/
      dockerfile: Dockerfile-nginx
    ports: 
      - "9003:80"
      - "22:22"
    volumes:
      - ./docker-files/nginx/deyapps-web:/home/remote_user/deyapps-web/
    networks:
      - network_ci

networks:
  network_ci:

volumes:
  sonarqube-conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube-bundled-plugins:
  postgresql17:
  postgresql17_data:
  jenkins_data: