FROM nginx

LABEL DeyJG <dey125r@gmail.com>

EXPOSE 22 80

RUN apt-get update && \
    apt-get install -y --no-install-suggests --no-install-recommends \
      openssh-server \
      iputils-ping \
      vim && \
    apt-get clean

ARG user_name='remote_user' && \
    path_deploy='deyapps-web'

RUN useradd -m -p $(perl -e 'print crypt($ARGV[0], "password")' '1234') $user_name && \
    mkdir /home/$user_name/.ssh && \
    mkdir /home/$user_name/$path_deploy && \
    mkdir /home/$user_name/$path_deploy/www &&\
    mkdir /home/$user_name/$path_deploy/backup

COPY ./nginx/keys/remote-key.pub /home/$user_name/.ssh/authorized_keys

RUN chown $user_name:$user_name -R /home/$user_name && \
    chown $user_name:$user_name -R /home/$user_name/$path_deploy/www && \
    chmod 600 /home/$user_name/.ssh/authorized_keys && \
    chmod 700 /home/$user_name/.ssh && \
    chmod 700 /home/$user_name/$path_deploy

COPY ./nginx/config/deyappshome.conf /etc/nginx/conf.d/default.conf

CMD service ssh start && \
    /docker-entrypoint.sh nginx -g 'daemon off;'